# Generated by Django 4.0.5 on 2022-06-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0004_add_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='regular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
            ],
        ),
    ]
