# Generated by Django 4.0.5 on 2022-06-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_add_vehicle'),
        ('booking', '0002_washing_and_cleaning_tyres_running_repair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='brakes',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='cable_replacement',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='regular',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='running_repair',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='tyres',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='washing_and_cleaning',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.battery')),
                ('brakes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.brakes')),
                ('cable_replacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.cable_replacement')),
                ('regular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.regular')),
                ('running_repair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.running_repair')),
                ('tyres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.tyres')),
                ('washing_and_cleaning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.washing_and_cleaning')),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
            ],
        ),
    ]
