# Generated by Django 4.0.5 on 2022-06-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_battery_vehicle_remove_brakes_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='price',
        ),
        migrations.RemoveField(
            model_name='brakes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cable_replacement',
            name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='service',
        ),
        migrations.RemoveField(
            model_name='regular',
            name='price',
        ),
        migrations.RemoveField(
            model_name='running_repair',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tyres',
            name='price',
        ),
        migrations.RemoveField(
            model_name='washing_and_cleaning',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.battery'),
        ),
        migrations.AddField(
            model_name='price',
            name='brakes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.brakes'),
        ),
        migrations.AddField(
            model_name='price',
            name='cable_replacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.cable_replacement'),
        ),
        migrations.AddField(
            model_name='price',
            name='regular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.regular'),
        ),
        migrations.AddField(
            model_name='price',
            name='running_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.running_repair'),
        ),
        migrations.AddField(
            model_name='price',
            name='tyres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.tyres'),
        ),
        migrations.AddField(
            model_name='price',
            name='washing_and_cleaning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.washing_and_cleaning'),
        ),
    ]
