# Generated by Django 4.0.5 on 2022-06-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_service_test_ser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ser',
        ),
        migrations.DeleteModel(
            name='service_test',
        ),
    ]
