# Generated by Django 4.0.5 on 2022-06-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_ser_delete_service_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='price',
            name='brakes',
        ),
        migrations.RemoveField(
            model_name='price',
            name='cable_replacement',
        ),
        migrations.RemoveField(
            model_name='price',
            name='regular',
        ),
        migrations.RemoveField(
            model_name='price',
            name='running_repair',
        ),
        migrations.RemoveField(
            model_name='price',
            name='tyres',
        ),
        migrations.RemoveField(
            model_name='price',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='price',
            name='washing_and_cleaning',
        ),
        migrations.DeleteModel(
            name='battery',
        ),
        migrations.DeleteModel(
            name='brakes',
        ),
        migrations.DeleteModel(
            name='cable_replacement',
        ),
        migrations.DeleteModel(
            name='price',
        ),
        migrations.DeleteModel(
            name='regular',
        ),
        migrations.DeleteModel(
            name='running_repair',
        ),
        migrations.DeleteModel(
            name='tyres',
        ),
        migrations.DeleteModel(
            name='washing_and_cleaning',
        ),
    ]
