# Generated by Django 4.0.5 on 2022-07-05 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0004_add_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0013_battery_brakes_cable_replacement_regular_and_more'),
        ('booking', '0009_remove_price_battery_remove_price_brakes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('price_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.price_model')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
            ],
        ),
    ]
