# Generated by Django 4.0.5 on 2022-07-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_cart_date_cart_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='states',
        ),
    ]
