# Generated by Django 4.0.5 on 2022-06-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0004_add_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='brakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cable_replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='running_repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tyres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='washing_and_cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(null=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.battery')),
                ('brakes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.brakes')),
                ('cable_replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.cable_replacement')),
                ('regular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.regular')),
                ('running_repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.running_repair')),
                ('tyres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.tyres')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
                ('washing_and_cleaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.washing_and_cleaning')),
            ],
        ),
    ]
