# Generated by Django 4.0.5 on 2022-06-30 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_test_ser'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ser'),
        ),
        migrations.AddField(
            model_name='price',
            name='service_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service_test'),
        ),
    ]
