# Generated by Django 4.0.5 on 2022-06-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_price_ser_price_service_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ser',
            new_name='package',
        ),
        migrations.RenameModel(
            old_name='service_test',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='ser',
            new_name='package',
        ),
        migrations.RemoveField(
            model_name='price',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='price',
            name='brakes',
        ),
        migrations.RemoveField(
            model_name='price',
            name='cable_replacement',
        ),
        migrations.RemoveField(
            model_name='price',
            name='regular',
        ),
        migrations.RemoveField(
            model_name='price',
            name='running_repair',
        ),
        migrations.RemoveField(
            model_name='price',
            name='tyres',
        ),
        migrations.RemoveField(
            model_name='price',
            name='washing_and_cleaning',
        ),
        migrations.DeleteModel(
            name='battery',
        ),
        migrations.DeleteModel(
            name='brakes',
        ),
        migrations.DeleteModel(
            name='cable_replacement',
        ),
        migrations.DeleteModel(
            name='regular',
        ),
        migrations.DeleteModel(
            name='running_repair',
        ),
        migrations.DeleteModel(
            name='tyres',
        ),
        migrations.DeleteModel(
            name='washing_and_cleaning',
        ),
    ]
