# Generated by Django 4.0.5 on 2022-06-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_ser_package_rename_service_test_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='service_test',
            new_name='service',
        ),
    ]
