# Generated by Django 4.0.5 on 2022-06-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_price_price_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_model',
            name='service',
        ),
    ]
