# Generated by Django 4.0.5 on 2022-07-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_package_service_alter_price_model_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='brakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cable_replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='running_repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tyres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='washing_and_cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('Summary', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price_model',
            name='package',
        ),
        migrations.RemoveField(
            model_name='price_model',
            name='service',
        ),
        migrations.DeleteModel(
            name='package',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.AddField(
            model_name='price_model',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.battery'),
        ),
        migrations.AddField(
            model_name='price_model',
            name='brakes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.brakes'),
        ),
        migrations.AddField(
            model_name='price_model',
            name='cable_replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.cable_replacement'),
        ),
        migrations.AddField(
            model_name='price_model',
            name='regular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.regular'),
        ),
        migrations.AddField(
            model_name='price_model',
            name='running_repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.running_repair'),
        ),
        migrations.AddField(
            model_name='price_model',
            name='tyres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.tyres'),
        ),
        migrations.AddField(
            model_name='price_model',
            name='washing_and_cleaning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.washing_and_cleaning'),
        ),
    ]
