# Generated by Django 4.0.5 on 2022-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_brands_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
