# Generated by Django 4.0.5 on 2022-07-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_brands_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_image/'),
        ),
    ]
